//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saving
    {
        public int SavingId { get; set; }
        public decimal Saving1 { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
